### ISSUE TITLE
"Error response: 408"

### ISSUE THREAD

**Issue by moshner** [onokje/node-red-contrib-tesla#20]
My automations all failed today, they are giving me an "Error response: 408" every time they try to connect. I have tried:

1. Updating my manual api token
2. opening the Tesla app on my phone: It still connect

No change. Any ideas why this would fail now?

**Comment by onokje** [comment]
A 408 response usually means that the Tesla API backend cannot contact your device/car in time. It is fairly normal. Just try it again a few times. I don't think it is related to authentication, because you would get another error then (401). 

It varies from time to time how stable it is. I get 408 responses in my flow all the time, sometimes dozens a day, sometimes none.

**Comment by moshner** [comment]
Interesting. I haven't had a non-408 response since 8/31. Every single request is always 408. I wonder if there isn't something else going on. Car has premium connectivity and in the evenings it is connected to my home wifi.

**Comment by moshner** [comment]
...and of course it suddenly worked again for me as soon as I posted this comment.

**Comment by bastelbert** [comment]
Does anyone else get the 408 error these days? 
On Tuesday everything worked fine, today I only get "Error response: 408"
